version: '3.9'

services:
  nginx:
    image: nginx:alpine
    container_name: hpc-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - fastapi
    networks:
      - hpc-net

  postgres:
    image: postgres:16
    container_name: hpc-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: hpcuser
      POSTGRES_PASSWORD: ***REMOVED***
      POSTGRES_DB: hpc_portal
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hpc-net

  fastapi:
    build: ./backend
    container_name: hpc-fastapi
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - postgres
    networks:
      - hpc-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: hpc-keycloak
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/hpc_portal
      KC_DB_USERNAME: hpcuser
      KC_DB_PASSWORD: ***REMOVED***
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ***REMOVED***
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - hpc-net

volumes:
  postgres-data:

networks:
  hpc-net:
    driver: bridge
