events { worker_processes auto; }

http {
  server {
    listen 80;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name localhost;

    # TLS vers le client (navigateur)
    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    # Route API → FastAPI avec mTLS
    location /api/ {
      proxy_pass          https://hpc-fastapi:8000;
      proxy_ssl_certificate         /etc/nginx/certs/client.crt;
      proxy_ssl_certificate_key     /etc/nginx/certs/client.key;
      proxy_ssl_trusted_certificate /etc/nginx/certs/ca.crt;
      proxy_ssl_verify    on;
      proxy_set_header    Host $host;
      proxy_set_header    X-Real-IP $remote_addr;
    }

    # Route / → Frontend
    location / {
      proxy_pass http://hpc-frontend:3000;
      proxy_set_header Host $host;
    }

    # Health check Nginx lui-même
    location /nginx-health {
      return 200 'nginx ok';
      add_header Content-Type text/plain;
    }
  }
}
